In [2]:
mydict={1:"v"}


In [3]:
mydict

{1: 'v'}

In [4]:
mydict[1]

'v'

In [9]:
for i in range(1,10,1):
 print(i)

1
2
3
4
5
6
7
8
9


In [10]:
import numpy as np

In [11]:
mylist=[1,2,3]

In [14]:
arr=np.array(mylist)

In [15]:
arr

array([1, 2, 3])

In [16]:
mylist=[[1,2,3],[4,5,6],[7,8,9]]
mylist


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [20]:
arr=np.array(mylist)

In [21]:
arr[1][1]

5

In [23]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [29]:
np.ones((3,3))*5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [34]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [33]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
np.random.rand(5,5)

array([[0.9332885 , 0.78113136, 0.51437198, 0.41064708, 0.08449965],
       [0.62308526, 0.03234551, 0.12216348, 0.51525125, 0.82322462],
       [0.8888702 , 0.23294507, 0.99018885, 0.80100824, 0.65439053],
       [0.20459753, 0.78170279, 0.68305214, 0.38586113, 0.40142867],
       [0.62730596, 0.69133301, 0.82210847, 0.10780895, 0.65735906]])

In [38]:
np.random.randn(5,5)

array([[-0.34898762,  0.23861813,  0.89270353,  0.64121526, -0.55022238],
       [ 0.33915061, -0.89270698, -1.84830602,  0.54712893,  0.75758502],
       [ 0.40087432, -0.55805029,  2.01703837,  1.02605205, -1.00788877],
       [ 1.22425321,  0.27590215,  0.41089799, -2.08052552, -1.36865651],
       [-0.69112543, -0.09337754, -1.09921683,  1.39456211, -1.0389301 ]])

In [41]:
np.random.randint(1,100,10)

array([72, 97, 86, 82,  7,  8, 66, 56, 45,  3])

In [42]:
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
arr1=np.arange(25)

In [48]:
arr1.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [50]:
arr.max()

9

In [51]:
arr.min()

1

In [52]:
arr.argmax()

8

In [53]:
arr.argmin()

0

In [54]:
arr.shape

(3, 3)

In [67]:
for i in range(10,50,2):
 print(i)

10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48


In [62]:
arr2=np.arange(10,50,2)

In [63]:
even=np.array(arr2)

In [64]:
even

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [77]:
list1=np.arange(0,9)

In [78]:
list1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [81]:
list1.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [91]:
tanya=np.arange(0,1,100)

In [92]:
tanya.reshape(10,10)

ValueError: cannot reshape array of size 1 into shape (10,10)

In [96]:
arr[:3]=100

In [97]:
arr


array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [98]:
hello=[1,2,3,4,5,6,7,8,9,10]

In [99]:
hello[0:5]

[1, 2, 3, 4, 5]

In [100]:
hello[::-1]

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [101]:
hello[0:5]=100

TypeError: can only assign an iterable

In [104]:
bye=np.array(hello)

In [105]:
bye[0:5]=100

In [106]:
bye

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [107]:
a=np.arange(0,25).reshape(5,5)

In [108]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [109]:
a[0:4,0:4]

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13],
       [15, 16, 17, 18]])

In [111]:
a[3:,3:]

array([[18, 19],
       [23, 24]])

In [115]:
b=np.arange(0,10)

In [117]:
c=np.array(b)

In [118]:
c>4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [119]:
bool_arr=c>4

In [120]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [122]:
c[bool_arr]

array([5, 6, 7, 8, 9])

In [155]:
np.arange(1,101).reshape(10,10)/float(100)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [154]:
float(1)/float(2)

0.5

In [140]:
tanya=np.arange(0.01,1.01,0.01)

In [141]:
tanya.reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])